audio = {
    "audioID": "UUID",
    "fk_fragment_id": "UUID",
    "audio_source": "str",
    "duration": "float",
    "sample_rate": "int",
    "bit_depth": "int",
    "channels": "int",
    "file_format": "str",
    "frequency_spectrum": "dict[str, float]",
    "fundamental_frequency": "float",
    "harmonics": "list[float]",
    "spectral_centroid": "float",
    "spectral_rolloff": "float",
    "amplitude_envelope": "list[float]",
    "peak_amplitude": "float",
    "rms_amplitude": "float",
    "dynamic_range": "float",
    "onset_times": "list[float]",
    "tempo": "float",
    "beat_positions": "list[float]",
    "rhythm_pattern": "str",
    "spatial_position": "str",
    "distance_cues": "float",
    "reverb_amount": "float",
    "speech_detected": "bool",
    "voice_characteristics": "dict[str, float]",
    "harmonic_resonance_detected": "bool",
    "quantum_frequency_signatures": "list[float]",
    "melodic_patterns": "list[str]",
    "rhythmic_patterns": "list[str]",
    "timbral_signatures": "list[str]",
}
