psychic_journey = {
    "psychic_id": "UUID",
    "psychic_event_type": "enum['precognition', 'telepathy', 'clairvoyance', 'clairaudience', 'empathic', 'channeling', 'astral_projection', 'lucid_dreaming', 'dimensional_phasing', 'guide_connections', 'creator_connection']",
    "psychic_experience": "str",
    "psychic_onset_time": "datetime",
    "psychic_duration": "timedelta",
    "colours": "dict[str, int]",
    "geometric_forms": "dict[str, int]",
    "dimensional_quality": "enum['3D', '2D', '1D', '0D']",
    "spatial_relationships": "dict[str, int]",
    "temporal_relationships": "dict[str, int]",
    "colour_harmonies": "dict[str, int]",
    "numbers": "dict[str, int]",
    "sensations": "dict[str, int]",
    "thoughts": "dict[str, int]",
    "visions": "dict[str, int]",
    "epiphanies": "dict[str, int]",
    "patterns": "dict[str, int]",
    "messages": "dict[str, int]",
    "connections": "dict[str, int]",
    "immediate_knowings": "dict[str, int]",
    "certainty_level": "dict[str, float]",
    "consciousness_state": "enum['awake', 'dreaming', 'altered']",
    "altered_state_depth": "float",
    "meditation_depth": "float",
    "lucidity_level": "float",
    "energy_interactions": "dict[str, int]",
    "glyph_needed": "bool",
    "entities_perceived": "dict[str, int]",
    "entity_descriptions": "dict[str, int]",
    "entity_interactions": "dict[str, int]",
    "entity_intentions": "dict[str, int]",
    "entity_energy_signature": "dict[str, int]",
    "psychic_protection": "enum['active', 'passive', 'none']",
    "protection_effectiveness": "float",
    "intrusion_attempts": "int",
    "protection_methods_active": "list[str]",
    "vulnerability_detected": "bool",
    "boundary_dissolution": "float",
    "synchronicities": "dict[str, int]",
    "coincidences": "dict[str, int]",
    "omissions": "dict[str, int]",
    "additions": "dict[str, int]",
    "corrections": "dict[str, int]",
    "aberrations": "dict[str, int]",
    "anomalies": "dict[str, int]",
    "paradoxes": "dict[str, int]",
    "reflections": "dict[str, int]",
}